trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
    displayName: 'Build Project with Maven'

  - script: |
      echo "Running JUnit tests"
      mvn test
    displayName: 'Run JUnit Tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/target/surefire-reports/*.xml'
      testRunTitle: 'JUnit Test Results'
