CREATE TABLE T_LDB_EMPRESA (
    ID_EMPRESA BIGINT PRIMARY KEY IDENTITY(1,1),
    NOME VARCHAR(255) NOT NULL,
    CNPJ VARCHAR(14) UNIQUE NOT NULL,
    ENDERECO VARCHAR(255),
    TELEFONE VARCHAR(15)
);

CREATE TABLE T_LDB_BRINQUEDO (
    ID_BRINQUEDO BIGINT PRIMARY KEY IDENTITY(1,1),
    NM_BRINQUEDO VARCHAR(255),
    TP_BRINQUEDO VARCHAR(255),
    CL_BRINQUEDO VARCHAR(255),
    TM_BRINQUEDO VARCHAR(255),
    PR_BRINQUEDO DECIMAL(10, 2),
    ID_EMPRESA BIGINT NOT NULL,
    FOREIGN KEY (ID_EMPRESA) REFERENCES T_LDB_EMPRESA(ID_EMPRESA) ON DELETE CASCADE
);

CREATE TABLE T_LDB_USUARIO (
    ID_USUARIO BIGINT PRIMARY KEY IDENTITY(1,1),
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

CREATE SEQUENCE seq_id_empresa
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

CREATE SEQUENCE seq_id_brinquedo
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;

CREATE SEQUENCE seq_id_usuario
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    MAXVALUE 2147483647
    CACHE 1;
